### ISSUE TITLE
Game crash taking portal back to present time

### ISSUE THREAD

**Issue by littlebalup** [usineur/Zelda3T#1]
Hi,
Game crash (C2-12828-1) when we take the teleportation portal to go back to the present time.
![sscf8yfsspiyatiotwuogg](https://user-images.githubusercontent.com/6732619/31575802-d37ee8be-b0ee-11e7-9602-25b5db2a3f1b.png)

Save file for test:
[savefile.zip](https://github.com/usineur/Zelda3T/files/1384657/savefile.zip)

I transfered this save to Windows build (http://www.zeldaroth.fr/fichier/Zelda3T.exe), then taken the portal without issue, then saved and copied back the save on the VITA. This time the game crash when loading the save.
Seems something in the "present time" is wrong...

**Comment by usineur** [comment]
Could you please try this [eboot.bin](ferb.fr/vita/eboot.bin) ?

**Comment by littlebalup** [comment]
It seems to work great :)
Thx

**Comment by usineur** [comment]
Alright... I will push a fix asap.

For now, there is a side effect i can't explain (sound doesn't restore properly when pressing PS Vita "Home" button).

**Comment by usineur** [comment]
Ok, finally found the problem.

I just commited the modifications.

You also need to overwrite a music file: [Nuit.ogg](https://1fichier.com/?5ek4ql5l3u) into `ux0:data/z3t/data/music`
The previous one was ~19 Mo and it was the original cause of your crash.

**Comment by littlebalup** [comment]
Nice! I didn't had time yet to look deeper your last commits. I'll do asap. If you used new lib, please send me your pre-compiled.

**Comment by usineur** [comment]
Here there are: [sdl_mikmod.zip](https://github.com/usineur/Zelda3T/files/1387362/sdl_mikmod.zip)

**Comment by littlebalup** [comment]
Thank you,

I have an issue making the vpk : https://prnt.sc/gy5oyy
Seems too much files that generate a too long command line for vita-pack-vpk. Do you have the same? I'm using msys2 on win7... maybe a limitation there. What's your environment?

**Comment by usineur** [comment]
I'm on Linux.

Latest revision i guess. Try 73b19eaf97ca5b6f57bd9c3c45a791e9948ae196 (git checkout)

**Comment by littlebalup** [comment]
Yeah, that's crappy msys2 memory limitation for args : http://prntscr.com/gy9647
You should have much more memory allocation on your linux distro.
Where arguments generated by cmake for vita-pack-vpk with all the data files is more than 50000 bytes (UTF-8, depending of path lenght).
Anyway, this is totally off topic. 
Your changes work like a charm. Many thx. I close this issue.
