### ISSUE TITLE
Crash when going to "jurassic" age (and probably to "apocalypse" age to)

### ISSUE THREAD

**Issue by littlebalup** [usineur/Zelda3T#2]
You can reproduce it using this save [3t2.zip](https://github.com/usineur/Zelda3T/files/1391913/3t2.zip)
then playing two time the inverted song with the ocarina. You shoud arrive to jurassic age then game crash where it is supposed to bring you back to the "snow" age.

Edit: also tested with an old build (with ogg musics), same issue. So, seems not related to your latest changes.

Edit2: I just got the accelerated song. So, there is also a crash when going to the futur age. And that is more weird than the jurassic. New save: [3t2.zip](https://github.com/usineur/Zelda3T/files/1392199/3t2.zip)
Play two times the accelerated song to reproduce the crash.

Edit3: In fact it seems the crash appear when we play two time ocarina to change age. So, as exemple, from the save above:
- Playing two times the accelerated song  = crash
- Playing one time the accelerated then one time the inverted song = crash
- Playing one time the accelerated song then save and quit, then load save and play the accelerated song again : works.
It smell another memory leak ...

**Comment by usineur** [comment]
1a784e597d86d9878f0fe1615664a8271334265b should be ok

**Comment by littlebalup** [comment]
I'll test that right now. But as I mentionned above in the first edit, about the jurasic age, I tested on an old build (before you changed this) with the same bug.

**Comment by usineur** [comment]
Just test the new save. Seems ok to me.

**Comment by littlebalup** [comment]
oh, sorry, I missed to change the listtable file... I try again

**Comment by littlebalup** [comment]
Ok, seems ok for me to :)

**Comment by littlebalup** [comment]
P.S: you should have look to the small corrections I made in the text.cpp about the command description, to add it to your next release : https://github.com/littlebalup/Zelda3T/commit/eeb5f5928d5b1202f323c5ade1d28375dfc2d3f0#diff-7650da861401afff18b70cd3c36616fc
https://github.com/littlebalup/Zelda3T/commit/4fc8556f1080163db639d83cd2e8a70c1bb49a29#diff-7650da861401afff18b70cd3c36616fc
https://github.com/littlebalup/Zelda3T/commit/19c6fd101b36e026a54a7f2d4a4bd80c43e4a316#diff-7650da861401afff18b70cd3c36616fc

I also made a small change here to prevent to open the map when using the L+R combo : https://github.com/littlebalup/Zelda3T/commit/19c6fd101b36e026a54a7f2d4a4bd80c43e4a316#diff-9c4e99ac0bc02920860d539a47e9d03e

**Comment by littlebalup** [comment]
One more small correction in text : https://github.com/littlebalup/Zelda3T/commit/22b2cfe656d3d6ae1e0c40aadfc3fe0a8cfaeec0#diff-7650da861401afff18b70cd3c36616fc

**Comment by usineur** [comment]
Thx, i will look at that
