### ISSUE TITLE
Need compile instructions

### ISSUE THREAD

**Issue by NicolasR** [usineur/Zelda3T#4]
Hello,

Could you please give more information about how to compile sources ?
I tried for days to compile but unable to link with sdl.

**Comment by usineur** [comment]
Pretty sure you try to link with SDL2, for this port, you need:

 - SDL 1.2: https://github.com/Cpasjuste/SDL-Vita/tree/SDL12
 - SDL_image:  [Archive](https://www.libsdl.org/projects/SDL_image/release/SDL_image-1.2.12.tar.gz) + [Makefile](https://www.ferb.fr/vita/makefiles/Makefile.vita.SDL_image-1.2)
 - SDL_gfx: [Archive](https://sourceforge.net/projects/sdlgfx/) + [Makefile](https://www.ferb.fr/vita/makefiles/Makefile.vita.SDL_gfx-2.0.25)
 - libmikmod: https://www.github.com/usineur/libmikmod
 - SDL_mixer: [Archive](https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz) + [Makefile](https://www.ferb.fr/vita/makefiles/Makefile.vita.SDL_mixer-1.2.12)

**Comment by NicolasR** [comment]
And you are perfectly right.
Now I have an error:
`/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/7.2.0/../../../../arm-vita-eabi/lib/libvita2d.a(vita2d.o): In function `vita2d_common_dialog_update':
(.text+0xeba): undefined reference to `sceCommonDialogUpdate'
collect2: error: ld returned 1 exit status
CMakeFiles/Zelda3T.dir/build.make:666 : la recette pour la cible « Zelda3T » a échouée
make[2]: *** [Zelda3T] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/Zelda3T.dir/all » a échouée
make[1]: *** [CMakeFiles/Zelda3T.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

**Comment by usineur** [comment]
add `SceCommonDialog_stub` into `target_link_libraries` of CMakeLists.txt

**Comment by NicolasR** [comment]
Ok it works now.
Thanks for your work and your help !

**Comment by usineur** [comment]
No problem. Feel free to close this issue.

**Comment by NicolasR** [comment]
Hello,

I got new problems with last release.
I compiled VitaGL, SDL_VitaGL but go some errors when compiling Zelda3T:

**error: 'SDL_Shader' does not name a type
error: 'SDL_SetVideoShader' was not declared in this scope
error: SDL_SHADER_NONE' was not declared in this scope
error: 'SDL_SHADER_SHARP_BILINEAR_SIMPLE' was not declared in this scope**
...

Could not find at all where this elements are declared.

**Comment by usineur** [comment]
Hi,

It seems that some  headers are not updated in your vitasdk

https://github.com/Rinnegatamante/SDL-Vita/commit/9a44958a4a522bd63ce0f35411b9ec12c36744dc

Make sure you to do 'make  -f Makefile.vita install'. Copying the libSDL.a only is not enough

**Comment by NicolasR** [comment]
I forgot this one. I used your SDL-Vita fork only.
It's working now. 

Thank you.
