### ISSUE TITLE
Freezing on Rupee guy.

### ISSUE THREAD

**Issue by TULOA** [usineur/Zelda3T#9]
So my game crashed after talking to the guy that gives you money for seeing new enemies.
After which I saved the game while the money was adding up but then talking to him from there causes a freeze. No crash logs or such.

If you get full currency and talk to him it doesnt freeze.

Not sure what this is about.
[RupeeFreeze.zip](https://github.com/usineur/Zelda3T/files/2150614/RupeeFreeze.zip)

**Comment by usineur** [comment]
Freeze fix, you can try this [eboot.bin](https://www.ferb.fr/vita/eboot.bin)

**Comment by TULOA** [comment]
Yup that got it. Thanks.
